Repository B-AROL-O/FREISA, pull requests merged in 2023-12, with the labels that each got.

#4 [FEAT]: Add Mini Pupper 2 demo code and technical report for FREISA
  code/mini-pupper-2/ReadMe.md
  code/mini-pupper-2/demo.py
  code/mini-pupper-2/test-gpio-servo.py
  code/mini-pupper-2/test-haptic-power-readings.py
  code/requirements.txt
Labels: enhancement

#9 [FEAT]: README.md: Add link to Hackster from cover image
  README.md
Labels: documentation, enhancement

#11 Update README.md after nomination
  README.md
Labels: documentation, enhancement, help wanted

#12 README.md: Fix typo
  README.md
Labels: bug, documentation

#13 [FEAT]: README.md: Add chapter: What is FREISA
  .github/linters/.markdown-lint.yml
  README.md
  assets/2023-12-13-freisa-databeers.png
Labels: documentation, enhancement
