Repository B-AROL-O/FREISA, pull requests merged in 2025-08, with the labels that each got.

#53 feat: add .gitattributes for line ending normalization
  .gitattributes
Labels: enhancement

#55 chore(devcontainer): update devcontainer.json
  .devcontainer/devcontainer.json
  .github/dependabot.yml
  .github/linters/.jscpd.json
  .github/linters/.markdown-lint.yml
  .github/workflows/linter.yml
  README.md
  code/README.md
  code/conv-heic2png/README.md
  code/depthai-docker/README.md
  code/jupyterlab-container/docker-compose.yaml
  code/oak-d-lite-module/README.md
  code/oak-d-lite-module/config/models.json
  code/oak-d-lite-module/config/serv_config.json
  code/test-cubbit-ds3/README.md
  docs/README.md
Labels: enhancement

#57 docs: add FREISA API documentation
  code/oak-d-lite-module/README.md
  docs/apis.md
Labels: documentation

#24 [FEAT]: Add assets for FREISA
  assets/FREISAQR.png
  assets/FREISAQR.svg
  assets/FREISA_bitmap.svg
  assets/FREISA_bitmap_trans.png
  assets/FREISA_bitmap_white.png
  assets/FREISA_logo_trans.png
  assets/logo_white.jpg
Labels: documentation, enhancement
