Repository B-AROL-O/FREISA, pull requests merged in 2025-09, with the labels that each got.

#56 feat: add program to test new FREISA faces
  code/test-freisa-faces/python_api_display.py
  code/test-freisa-faces/rsync_and_run_app.sh
Labels: enhancement

#64 docs: update section "The Team behind FREISA" in top-level README.md
  README.md
Labels: documentation

#59 docs(howto): add howto-backup-rpi-images.md
  docs/howto/howto-backup-rpi-images.md
  docs/howto/images/balenaetcher-01.png
  docs/howto/images/balenaetcher-02.png
  docs/howto/images/balenaetcher-03.png
Labels: documentation, enhancement

#63 feat: create devcontainer definition launching VNC + noVNC
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/entrypoint.sh
  .devcontainer/setup.sh
  docs/howto/howto-set-up-devcontainer.md
Labels: enhancement, help wanted

#70 Delete assets/FREISAQR.png
  assets/FREISAQR.png
  assets/FREISAQR.svg
  assets/qr_code_freisa.png
Labels: bug, enhancement, help wanted

#82 feat: add photos of FREISA dog with Elisa
  assets/non-free/elisa_freisa.jpeg
  assets/non-free/elisa_redpuppy_happy.jpeg
  assets/non-free/elisa_redpuppy_serious.jpeg
Labels: documentation

#85 feat: update top-level README.md
  README.md
  assets/2025-08-06-openai-devpost-com.png
Labels: documentation, enhancement, help wanted

#87 feat: make FREISA-GPT main code public
  .devcontainer/Dockerfile
  .gitmodules
  code/FREISA-GPT/.flake8
  code/FREISA-GPT/.python-version
  code/FREISA-GPT/README.md
  code/FREISA-GPT/main.py
  code/FREISA-GPT/pyproject.toml
  code/FREISA-GPT/servers_config.json
  code/FREISA-GPT/src/mcp_client_pupper/__init__.py
  code/FREISA-GPT/src/mcp_client_pupper/main.py
  code/FREISA-GPT/src/mcp_client_pupper/mcp_client.py
  code/FREISA-GPT/src/mcp_client_pupper/puppy_voice_assistant.py
  code/FREISA-GPT/src/mcp_client_pupper/utils/llm_client.py
  code/FREISA-GPT/src/mcp_client_pupper/utils/math.py
  code/FREISA-GPT/src/mcp_client_pupper/utils/puppy_interaction.py
  code/FREISA-GPT/src/mcp_client_pupper/utils/text_color.py
  code/FREISA-GPT/src/mcp_server_pupper/__init__.py
  code/FREISA-GPT/src/mcp_server_pupper/main.py
  code/FREISA-GPT/src/mcp_server_pupper/utils/network_utils.py
  code/FREISA-GPT/src/mcp_server_pupper/utils/websocket_manager.py
  code/FREISA-GPT/uv.lock
  code/puppy-state-api/main.py
Labels: enhancement

#92 feat: test performances of Ollama on Raspberry Pi 5B
  assets/2025-09-22-ollama-run-qwen3.jpg
  code/open-webui/compose.yml
  docs/howto/howto-install-ollama-raspberry-pi-5b.md
Labels: enhancement
